# This workflow will build a NodeJS application

name: Node CI with Yarn

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 6.11.5
    - name: Install Dependencies
      run: yarn install && cd react-ui && yarn install && yarn install --only=dev --no-shrinkwrap && npm run build
    - name: Start Service