# This workflow will build a NodeJS application

name: Node CI with Yarn

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 6.11.5
    - name: Install and build server dependencies
      run: yarn install && npm run build
    - name: Install and build client dependencies
      run: npm run heroku-postbuild